Repository NCIOCPL/clinical-trials-search-app, pull requests merged in 2022-07, with the labels that each got.

#540 (#539) Try a new search retains values
  src/views/ResultsPage/ResultsPage.jsx
Labels: Needs Technical Review, Passed QA Review

#542 (#528) Make print service location configurable
  public/index.html
  src/index.js
  src/views/ResultsPage/PrintModalContent.jsx
Labels: Needs Technical Review

#546 (#545) Print Modal Fix on ODE
  public/index.html
  src/components/atomic/Modal/Modal.jsx
Labels: Passed QA Review

#547 (#543) Fix fonts import to correctly display fonts
  public/__nci-dev__common.css
Labels: Needs Technical Review, Passed QA Review

#556 (#530) Strip quotes from incoming Keywords And Phrases field
  src/utilities/queryStringToSearchCriteria.js
Labels: Needs Technical Review, Passed QA Review

#553 (#552) Duplicate Delighters on Invalid Param Page - Mobile Breakpoint
  src/views/ResultsPage/ResultsPage.jsx
Labels: Needs Technical Review, Passed QA Review

#557 (#555) Cancer type related findings list not populated in advanced form
  src/services/api/clinical-trials-search-api/__tests__/getFindings.test.js
  src/store/actionsV2/__tests__/getFindingsAction.test.js
  src/store/actionsV2/getFindingsAction.js
  support/src/mock-clinical-trials/diseases.js
Labels: Needs Technical Review, Passed QA Review

#536 (#532) Double horizontal lines are displayed when there is no pager at 1024px and lower
  src/views/ResultsPage/ResultsPage.jsx
  src/views/ResultsPage/ResultsPage.scss
  src/views/ResultsPage/ResultsPageHeader.jsx
Labels: Needs Technical Review, Passed QA Review

#565 #560 Duplicate NCI study protocol identifier not showing in Secondary IDs list
  src/views/TrialDescriptionPage/TrialDescriptionPage.jsx
Labels: Needs Technical Review, Passed QA Review

#563 (#562) Add friendly text for trials with trial type OTHER
  cypress/integration/TrialDescriptionPage/GeneralPageComponents.feature
  cypress/integration/TrialDescriptionPage/GeneralPageComponents/index.js
  src/views/TrialDescriptionPage/TrialDescriptionPage.jsx
  src/views/TrialDescriptionPage/TrialDescriptionPage.scss
  support/mock-data/v2/trials/trial/NCI-2018-02261.json
Labels: Needs Technical Review, Passed QA Review

#559 (#558) Updated print service object
  cypress/integration/SearchResultsPage/PrintFunctionality.feature
  src/views/ResultsPage/PrintModalContent.jsx
Labels: Needs Technical Review
