Repository NCIOCPL/clinical-trials-search-app, pull requests merged in 2022-04, with the labels that each got.

#500 (#489) Out-of-bounds page number displays blank screen
  src/views/ResultsPage/ResultsPage.jsx
Labels: Needs Technical Review, Passed UX Review

#502 (#483) Remove clearForm dispatch from ResultsPage, TrialDescription Start Over fix
  src/views/ResultsPage/ResultsPage.jsx
  src/views/SearchPage/SearchPage.jsx
Labels: Needs Technical Review

#507 (#505) Blank Location on Search Results Page
  src/views/ResultsPage/ResultsListItem.jsx
Labels: Needs Technical Review

#482 (#446) Changed CTS.Print request
  cypress/integration/SearchResultsPage/PrintFunctionality.feature
  cypress/integration/SearchResultsPage/PrintFunctionality/index.js
  src/hooks/usePrintApi.js
  src/views/ResultsPage/PrintModalContent.jsx
Labels: Needs Technical Review

#506 (#193) Update zip to ZIP in all Zip Code references
  cypress/integration/AdvancedSearchPage/LocationSection/LocationByZipcode.feature
  cypress/integration/BasicSearchPage/BasicSearchPage.feature
  cypress/integration/BasicSearchPage/BasicSearchPage/index.js
  cypress/integration/Components/Autocomplete.feature
  cypress/integration/Components/Autocomplete/index.js
  src/components/search-modules/ZipCode/ZipCode.jsx
  src/constants/index.js
Labels: Needs Technical Review

#503 (#200) Error Page - Use Correct Form Type on Start Over
  cypress/integration/SearchResultsPage/GeneralPageComponents.feature
  src/views/ErrorPage/ErrorPage.jsx
Labels: Needs Technical Review

#501 (#494) Trial description shows blank page instead of invalid criteria page
  src/views/ResultsPage/ResultsPage.jsx
  src/views/TrialDescriptionPage/TrialDescriptionPage.jsx
Labels: Needs QA Review, Needs Technical Review, Needs UX Review
