Repository NCIOCPL/clinical-trials-search-app, pull requests merged in 2022-06, with the labels that each got.

#518 (#513) Modify delighter URLs not to point to specific generated sprite
  src/components/atomic/Delighter/Delighter.scss
  src/views/SearchPage/SearchPage.scss
  src/views/TrialDescriptionPage/TrialDescriptionPage.scss
Labels: Needs Technical Review, Passed QA Review

#521 #201 Modify Search from Trial Details Page
  cypress/integration/AdvancedSearchPage/AgeSection.feature
  cypress/integration/TrialDescriptionPage/GeneralPageComponents.feature
  cypress/integration/TrialDescriptionPage/GeneralPageComponents/index.js
  public/__nci-dev__common.css
  src/views/TrialDescriptionPage/TrialDescriptionPage.jsx
  src/views/TrialDescriptionPage/TrialDescriptionPage.scss
  support/mock-data/clinical-trial/NCI-2020-08118.json
  support/mock-data/v2/trials/trial/NCI-2020-08118.json
Labels: Needs Technical Review, Passed QA Review

#515 (#514) Update Browser Title to Use siteName Parameter
  cypress/integration/AdvancedSearchPage/AdvancedSearchForm.feature
  cypress/integration/Analytics/AdvancedTrialSearchPage.feature
  cypress/integration/Analytics/BasicTrialSearchPage.feature
  cypress/integration/Analytics/TrialDescriptionPage.feature
  cypress/integration/BasicSearchPage/BasicSearchPage.feature
  cypress/integration/SearchResultsPage/GeneralPageComponents.feature
  cypress/integration/SearchResultsPage/PrintFunctionality.feature
  cypress/integration/TrialDescriptionPage/GeneralPageComponents.feature
  cypress/integration/common/beforeEach.js
  public/index.html
  src/index.js
  src/views/ErrorPage/ErrorPage.jsx
  src/views/ResultsPage/ResultsPage.jsx
  src/views/SearchPage/SearchPage.jsx
  src/views/TrialDescriptionPage/TrialDescriptionPage.jsx
  support/mock-data/clinical-trials/C2989-response.json
Labels: Needs Technical Review, Passed UX Review, Passed QA Review

#535 (#413) Remove CTS v1 search client dependency
  package-lock.json
  package.json
  src/App.js
  src/index.js
Labels: Needs Technical Review
